AppBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        passwordHash:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: password_hash
        vat:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
